title: "RCOS Site"
description: "Built with Jekyll on GitHub Pages"
theme: minima

url: "https://legffy.github.io"   # no trailing slash
baseurl: "/rcos.github.io"         # repo path (leading slash, no trailing slash)

author: "Randy"
